package com.maheshvalue.order_management;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Customer")
public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CUSTOMER_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CUSTOMER_ID_GENERATOR", sequenceName = "CUSTOMER_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("customerName")
	private java.lang.String customerName;

	@org.kie.api.definition.type.Label("customerCode")
	private java.lang.String customerCode;

	public Customer() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(java.lang.String customerName) {
		this.customerName = customerName;
	}

	public java.lang.String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(java.lang.String customerCode) {
		this.customerCode = customerCode;
	}

	public Customer(java.lang.Long id, java.lang.String customerName,
			java.lang.String customerCode) {
		this.id = id;
		this.customerName = customerName;
		this.customerCode = customerCode;
	}

}