package com.maheshvalue.order_management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "CUSTOMER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CUSTOMER_ID_GENERATOR", sequenceName = "CUSTOMER_ID_SEQ")
	@org.kie.api.definition.type.Label("customerAddress")
	private java.lang.String customerAddress;

	@org.kie.api.definition.type.Label("customerGeneralDetail")
	private java.lang.String customerGeneralDetail;

	@org.kie.api.definition.type.Label("customerCompanyDetail")
	private java.lang.String customerCompanyDetail;

	@org.kie.api.definition.type.Label("returnData")
	private java.lang.String returnData;

	@org.kie.api.definition.type.Label("userExist")
	private java.lang.Boolean userExist;

	@org.kie.api.definition.type.Label("customerNo")
	private java.lang.String customerNo;

	@org.kie.api.definition.type.Label(value = "companyCode")
	private java.lang.String companyCode;

	public CustomerDetails() {
	}

	public java.lang.String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(java.lang.String customerAddress) {
		this.customerAddress = customerAddress;
	}

	public java.lang.String getCustomerGeneralDetail() {
		return this.customerGeneralDetail;
	}

	public void setCustomerGeneralDetail(java.lang.String customerGeneralDetail) {
		this.customerGeneralDetail = customerGeneralDetail;
	}

	public java.lang.String getCustomerCompanyDetail() {
		return this.customerCompanyDetail;
	}

	public void setCustomerCompanyDetail(java.lang.String customerCompanyDetail) {
		this.customerCompanyDetail = customerCompanyDetail;
	}

	public java.lang.String getReturnData() {
		return this.returnData;
	}

	public void setReturnData(java.lang.String returnData) {
		this.returnData = returnData;
	}

	public java.lang.Boolean getUserExist() {
		return this.userExist;
	}

	public void setUserExist(java.lang.Boolean userExist) {
		this.userExist = userExist;
	}

	public java.lang.String getCustomerNo() {
		return this.customerNo;
	}

	public void setCustomerNo(java.lang.String customerNo) {
		this.customerNo = customerNo;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	public CustomerDetails(java.lang.String customerAddress,
			java.lang.String customerGeneralDetail,
			java.lang.String customerCompanyDetail,
			java.lang.String returnData, java.lang.Boolean userExist,
			java.lang.String customerNo, java.lang.String companyCode) {
		this.customerAddress = customerAddress;
		this.customerGeneralDetail = customerGeneralDetail;
		this.customerCompanyDetail = customerCompanyDetail;
		this.returnData = returnData;
		this.userExist = userExist;
		this.customerNo = customerNo;
		this.companyCode = companyCode;
	}

}