package com.maheshvalue.order_management;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
public class CustomerDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("userExist")
	private java.lang.Boolean userExist;

	@org.kie.api.definition.type.Label("customerNo")
	private java.lang.String customerNo;

	@org.kie.api.definition.type.Label("companyCode")
	private java.lang.String companyCode;

	public CustomerDetails() {
	}

	public java.lang.Boolean getUserExist() {
		return this.userExist;
	}

	public void setUserExist(java.lang.Boolean userExist) {
		this.userExist = userExist;
	}

	public java.lang.String getCustomerNo() {
		return this.customerNo;
	}

	public void setCustomerNo(java.lang.String customerNo) {
		this.customerNo = customerNo;
	}

	public java.lang.String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(java.lang.String companyCode) {
		this.companyCode = companyCode;
	}

	public CustomerDetails(java.lang.Boolean userExist,
			java.lang.String customerNo, java.lang.String companyCode) {
		this.userExist = userExist;
		this.customerNo = customerNo;
		this.companyCode = companyCode;
	}

}