package com.maheshvalue.order_management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KeyBalanceDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "currency")
	private java.lang.String currency;
	@org.kie.api.definition.type.Label(value = "tCurrBal")
	private java.lang.Double tCurrBal;
	@org.kie.api.definition.type.Label(value = "locCurrcy")
	private java.lang.String locCurrcy;
	@org.kie.api.definition.type.Label(value = "spGlInd")
	private java.lang.String spGlInd;
	@org.kie.api.definition.type.Label(value = "lcBal")
	private java.lang.Double lcBal;
	@org.kie.api.definition.type.Label(value = "dbCrInd")
	private java.lang.String dbCrInd;

	public KeyBalanceDetails() {
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public java.lang.Double gettCurrBal() {
		return this.tCurrBal;
	}

	public void settCurrBal(java.lang.Double tCurrBal) {
		this.tCurrBal = tCurrBal;
	}

	public java.lang.String getLocCurrcy() {
		return this.locCurrcy;
	}

	public void setLocCurrcy(java.lang.String locCurrcy) {
		this.locCurrcy = locCurrcy;
	}

	public java.lang.String getSpGlInd() {
		return this.spGlInd;
	}

	public void setSpGlInd(java.lang.String spGlInd) {
		this.spGlInd = spGlInd;
	}

	public java.lang.Double getLcBal() {
		return this.lcBal;
	}

	public void setLcBal(java.lang.Double lcBal) {
		this.lcBal = lcBal;
	}

	public java.lang.String getDbCrInd() {
		return this.dbCrInd;
	}

	public void setDbCrInd(java.lang.String dbCrInd) {
		this.dbCrInd = dbCrInd;
	}

	public KeyBalanceDetails(java.lang.String currency,
			java.lang.Double tCurrBal, java.lang.String locCurrcy,
			java.lang.String spGlInd, java.lang.Double lcBal,
			java.lang.String dbCrInd) {
		this.currency = currency;
		this.tCurrBal = tCurrBal;
		this.locCurrcy = locCurrcy;
		this.spGlInd = spGlInd;
		this.lcBal = lcBal;
		this.dbCrInd = dbCrInd;
	}

}