package com.maheshvalue.order_management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderItems implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "product_id")
	private java.lang.String product_id;
	@org.kie.api.definition.type.Label(value = "product_qty")
	private java.lang.String product_qty;

	public OrderItems() {
	}

	public java.lang.String getProduct_id() {
		return this.product_id;
	}

	public void setProduct_id(java.lang.String product_id) {
		this.product_id = product_id;
	}

	public java.lang.String getProduct_qty() {
		return this.product_qty;
	}

	public void setProduct_qty(java.lang.String product_qty) {
		this.product_qty = product_qty;
	}

	public OrderItems(java.lang.String product_id, java.lang.String product_qty) {
		this.product_id = product_id;
		this.product_qty = product_qty;
	}

}