package com.maheshvalue.order_management;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "SaleOrder")
public class SaleOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SALEORDER_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SALEORDER_ID_GENERATOR", sequenceName = "SALEORDER_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "description")
	private java.lang.String description;

	@org.kie.api.definition.type.Label(value = "category")
	private java.lang.String category;

	@org.kie.api.definition.type.Label(value = "other")
	private java.lang.String other;

	@org.kie.api.definition.type.Label(value = "unitPrice")
	private java.lang.String unitPrice;

	@org.kie.api.definition.type.Label(value = "salePrice")
	private java.lang.String salePrice;

	@org.kie.api.definition.type.Label(value = "quantity")
	private java.lang.String quantity;

	@org.kie.api.definition.type.Label(value = "totalPrice")
	private java.lang.String totalPrice;

	public SaleOrder() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getOther() {
		return this.other;
	}

	public void setOther(java.lang.String other) {
		this.other = other;
	}

	public java.lang.String getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(java.lang.String unitPrice) {
		this.unitPrice = unitPrice;
	}

	public java.lang.String getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(java.lang.String salePrice) {
		this.salePrice = salePrice;
	}

	public java.lang.String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(java.lang.String quantity) {
		this.quantity = quantity;
	}

	public java.lang.String getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(java.lang.String totalPrice) {
		this.totalPrice = totalPrice;
	}

	public SaleOrder(java.lang.Long id, java.lang.String name,
			java.lang.String description, java.lang.String category,
			java.lang.String other, java.lang.String unitPrice,
			java.lang.String salePrice, java.lang.String quantity,
			java.lang.String totalPrice) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.category = category;
		this.other = other;
		this.unitPrice = unitPrice;
		this.salePrice = salePrice;
		this.quantity = quantity;
		this.totalPrice = totalPrice;
	}

}