package com.maheshvalue.order_management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SaleOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "SALEORDER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SALEORDER_ID_GENERATOR", sequenceName = "SALEORDER_ID_SEQ")
	@org.kie.api.definition.type.Label("address_id")
	private int address_id;

	@org.kie.api.definition.type.Label("payment_mode")
	private java.lang.String payment_mode;

	@org.kie.api.definition.type.Label("user_id")
	private int user_id;

	@org.kie.api.definition.type.Label("msfa2_id")
	private int msfa2_id;

	@org.kie.api.definition.type.Label("transaction_id")
	private java.lang.String transaction_id;

	@org.kie.api.definition.type.Label("route")
	private int route;

	@org.kie.api.definition.type.Label("order_process_by")
	private java.lang.String order_process_by;

	@org.kie.api.definition.type.Label("total_amount")
	private java.lang.String total_amount;

	@org.kie.api.definition.type.Label("isShipToOutlet")
	private boolean isShipToOutlet;

	@org.kie.api.definition.type.Label("order_items")
	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<com.maheshvalue.order_management.OrderItems> order_items;

	public SaleOrder() {
	}

	public int getAddress_id() {
		return this.address_id;
	}

	public void setAddress_id(int address_id) {
		this.address_id = address_id;
	}

	public java.lang.String getPayment_mode() {
		return this.payment_mode;
	}

	public void setPayment_mode(java.lang.String payment_mode) {
		this.payment_mode = payment_mode;
	}

	public int getUser_id() {
		return this.user_id;
	}

	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}

	public int getMsfa2_id() {
		return this.msfa2_id;
	}

	public void setMsfa2_id(int msfa2_id) {
		this.msfa2_id = msfa2_id;
	}

	public java.lang.String getTransaction_id() {
		return this.transaction_id;
	}

	public void setTransaction_id(java.lang.String transaction_id) {
		this.transaction_id = transaction_id;
	}

	public int getRoute() {
		return this.route;
	}

	public void setRoute(int route) {
		this.route = route;
	}

	public java.lang.String getOrder_process_by() {
		return this.order_process_by;
	}

	public void setOrder_process_by(java.lang.String order_process_by) {
		this.order_process_by = order_process_by;
	}

	public java.lang.String getTotal_amount() {
		return this.total_amount;
	}

	public void setTotal_amount(java.lang.String total_amount) {
		this.total_amount = total_amount;
	}

	public boolean isIsShipToOutlet() {
		return this.isShipToOutlet;
	}

	public void setIsShipToOutlet(boolean isShipToOutlet) {
		this.isShipToOutlet = isShipToOutlet;
	}

	public java.util.List<com.maheshvalue.order_management.OrderItems> getOrder_items() {
		return this.order_items;
	}

	public void setOrder_items(
			java.util.List<com.maheshvalue.order_management.OrderItems> order_items) {
		this.order_items = order_items;
	}

	public SaleOrder(
			int address_id,
			java.lang.String payment_mode,
			int user_id,
			int msfa2_id,
			java.lang.String transaction_id,
			int route,
			java.lang.String order_process_by,
			java.lang.String total_amount,
			boolean isShipToOutlet,
			java.util.List<com.maheshvalue.order_management.OrderItems> order_items) {
		this.address_id = address_id;
		this.payment_mode = payment_mode;
		this.user_id = user_id;
		this.msfa2_id = msfa2_id;
		this.transaction_id = transaction_id;
		this.route = route;
		this.order_process_by = order_process_by;
		this.total_amount = total_amount;
		this.isShipToOutlet = isShipToOutlet;
		this.order_items = order_items;
	}

}